# Change these first
owner: UsoliaDev # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: game-server-main
    slug: 游戏服务器[main]
    url: mc.usolia.net
    port: 25565
    check: "tcp-ping"
    ipv6: false
  - name: game-server-de-ber01
    slug: 游戏服务器[de-ber01]
    url: acc-de-ber01.infra.usolia.dev
    port: 25565
    check: "tcp-ping"
    ipv6: false
  - name: game-server-ru-mow01
    slug: 游戏服务器[ru-mow01]
    url: acc-ru-mow01.infra.usolia.dev
    port: 25565
    check: "tcp-ping"
    ipv6: false
  - name: forum
    slug: 社区论坛
    url: https://usolia.net
  - name: Wiki
    url: https://wiki.usolia.net
  - name: satellite
    slug: 卫星地图
    url: https://satellite.usolia.net


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.usolia.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "**Usolia 设施状态**"
  introMessage: "在这里查看各项服务的在线状态，以及即将进行的维护。"
  navbar:
    - title: status
      slug: 状态
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
