# Change these first
owner: UsoliaDev # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: game-server-main
    slug: "Game Server [main]"
    url: mc.usolia.net
    port: 25565
    check: "tcp-ping"
  - name: game-server-de-ber01
    slug: "Game Server [de-centre-1]"
    url: acc-de-ber01.infra.usolia.dev
    port: 25565
    check: "tcp-ping"
  - name: game-server-ru-mow01
    slug: "Game Server [ru-mow-1]"
    url: acc-ru-mow01.infra.usolia.dev
    port: 25565
    check: "tcp-ping"
  - name: forum
    slug: "Community Forum"
    url: https://usolia.net
  - name: Wiki
    url: https://wiki.usolia.net
  - name: satellite
    slug: "Satellite"
    url: https://satellite.usolia.net


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.usolia.net
  # baseUrl: /your-repo-name
  logoUrl: https://assets.usolia.net/status.usolia.net/assets/logo-status.png
  name: Status
  introTitle: "**Usolia 设施状态**"
  introMessage: "在这里查看各项服务的在线状态，以及即将进行的维护。"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: © 2018-2024 Usolia Network. All rights reserved.

status-website:
  theme: light
